import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Sargis Ter-Balyants's Website",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const messages = await getMessages();

    return (
        <NextIntlClientProvider messages={messages}>
            <html lang="en">
                <body className={roboto.className}>
                    <Header></Header>
                    {children}
                    <Footer></Footer>
                </body>
            </html>
        </NextIntlClientProvider>
    );
}
